# Generated by Django 5.1.5 on 2025-01-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Language', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('is_alive', models.BooleanField(default=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('number_of_books', models.IntegerField(default=0)),
                ('social_media_links', models.JSONField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('genres', models.ManyToManyField(related_name='authors', to='genres.genre')),
                ('languages', models.ManyToManyField(blank=True, related_name='authors', to='Language.language')),
            ],
        ),
    ]
