# Generated by Django 5.1.5 on 2025-02-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('books', models.ManyToManyField(blank=True, related_name='categories', to='books.book')),
            ],
        ),
    ]
