# Generated by Django 5.1.5 on 2025-08-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=5, null=True
            ),
        ),
    ]
