# Generated by Django 5.1.5 on 2025-08-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_book_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="rating",
        ),
    ]
