# Generated by Django 5.1.5 on 2025-08-25 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_remove_book_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format_name",
                    models.CharField(max_length=100, verbose_name="نوع فرمت"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="قیمت"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        verbose_name="شابک",
                    ),
                ),
                (
                    "page_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="تعداد صفحات"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="وزن (کیلوگرم)",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="books/covers/",
                        verbose_name="تصویر جلد",
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="موجودی")),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=5,
                        null=True,
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formats",
                        to="books.book",
                        verbose_name="کتاب",
                    ),
                ),
            ],
            options={
                "verbose_name": "فرمت کتاب",
                "verbose_name_plural": "فرمت\u200cهای کتاب",
                "unique_together": {("book", "format_name")},
            },
        ),
    ]
