# Generated by Django 5.1.5 on 2025-08-25 04:43

from django.db import migrations

def transfer_book_data(apps, schema_editor):
    """
    Transfers format-specific data from the Book model to the new BookFormat model.
    """
    Book = apps.get_model('books', 'Book')
    BookFormat = apps.get_model('books', 'BookFormat')

    for book in Book.objects.all():
        # Use the existing cover_type as the format name, with a default.
        # This logic assumes that if cover_type is blank, it's a standard paperback.
        # This can be adjusted based on the actual data characteristics.
        format_name = book.cover_type if book.cover_type else 'شومیز'

        # Create a new BookFormat instance for each existing book
        BookFormat.objects.create(
            book=book,
            format_name=format_name,
            price=book.price,
            isbn=book.isbn,
            page_count=book.page_count,
            weight=book.weight,
            cover_image=book.cover_image,
            stock=book.stock,
            discount=book.discount
        )

class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_bookformat"),
    ]

    operations = [
        migrations.RunPython(transfer_book_data),
    ]
