# Generated by Django 5.1.5 on 2025-08-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_migrate_book_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="book",
            name="cover_type",
        ),
        migrations.RemoveField(
            model_name="book",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="book",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="book",
            name="page_count",
        ),
        migrations.RemoveField(
            model_name="book",
            name="price",
        ),
        migrations.RemoveField(
            model_name="book",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="book",
            name="weight",
        ),
    ]
