# Generated by Django 5.1.5 on 2025-08-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_stocknotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookformat",
            name="preorder_end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ پایان پیش\u200cسفارش"
            ),
        ),
        migrations.AddField(
            model_name="bookformat",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_stock", "In Stock"),
                    ("out_of_stock", "Out of Stock"),
                    ("pre_order", "Pre-order"),
                ],
                default="in_stock",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
    ]
