# Generated by Django 5.1.5 on 2025-08-25 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
        ("books", "0009_remove_book_cover_image_remove_book_cover_type_and_more"),
        ("discounts", "0001_initial"),
        ("genres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="percentage",
        ),
        migrations.AddField(
            model_name="discount",
            name="applicable_authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="discounts",
                to="authors.author",
                verbose_name="نویسندگان خاص",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="applicable_books",
            field=models.ManyToManyField(
                blank=True,
                related_name="discounts",
                to="books.book",
                verbose_name="کتاب\u200cهای خاص",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="applicable_formats",
            field=models.ManyToManyField(
                blank=True,
                related_name="discounts",
                to="books.bookformat",
                verbose_name="فرمت\u200cهای خاص",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="applicable_genres",
            field=models.ManyToManyField(
                blank=True,
                related_name="discounts",
                to="genres.genre",
                verbose_name="ژانرهای خاص",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="max_uses",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="حداکثر تعداد استفاده (کل)"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="max_uses_per_customer",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="حداکثر استفاده برای هر مشتری"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="min_purchase_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="حداقل مبلغ خرید",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="times_used",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="تعداد دفعات استفاده شده"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="type",
            field=models.CharField(
                choices=[("PERCENTAGE", "درصد"), ("FIXED_AMOUNT", "مبلغ ثابت")],
                default="PERCENTAGE",
                max_length=20,
                verbose_name="نوع تخفیف",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="مقدار (درصد یا مبلغ)",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="کد تخفیف"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateTimeField(verbose_name="تاریخ پایان"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start_date",
            field=models.DateTimeField(verbose_name="تاریخ شروع"),
        ),
        migrations.CreateModel(
            name="DiscountUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("use_count", models.PositiveIntegerField(default=0)),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="discounts.discount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "استفاده از تخفیف",
                "verbose_name_plural": "استفاده از تخفیف\u200cها",
                "unique_together": {("discount", "user")},
            },
        ),
    ]
