# Generated by Django 5.1.5 on 2025-08-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_phone_number_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="custom_id",
        ),
    ]
