# Generated by Django 5.1.5 on 2025-02-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='province_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='residence_type',
            field=models.CharField(blank=True, choices=[('1', 'محل دائمی سکونت | مالک هستم | بیش از دو سال در این مکان هستم'), ('2', 'محل دائمی سکونت | مالک هستم | بیش از یکسال و کمتر از دو سال در این مکان هستم'), ('3', 'محل دائمی سکونت | مالک هستم | بزودی تغییر مکان می دهم'), ('4', 'محل دائمی سکونت | مستاجر هستم | بیش از یکسال در این مکان هستم'), ('5', 'محل دائمی سکونت | مستاجر هستم | کمتر از یکسال در این مکان هستم'), ('6', 'محل موقت سکونت | در ایران ساکن نیستم و ساکن کشور دیگری هستم'), ('7', 'محل موقت سکونت | مالک هستم | ساکن شهر دیگری هستم'), ('8', 'محل موقتی سکونت | نه مالک و نه مستاجر هستم | بزودی تغییر مکان می دهم'), ('9', 'محل دائمی کار و تجارت | مالک یا مستاجر هستم | بتازگی در این مکان هستم )کمتر از دوماه('), ('10', 'محل دائمی کار و تجارت | مالک هستم | بیش از یکسال در این مکان هستم'), ('11', 'محل دائمی کار و تجارت | مالک هستم | کمتر از یکسال در این مکان هستم )بیش از دو ماه('), ('12', 'محل دائمی کار و تجارت | مستاجر هستم | بیش از یکسال در این مکان هستم'), ('13', 'محل دائمی کار و تجارت | مستاجر هستم | کمتر از یکسال در این مکان هستم )بیش از دو ماه(')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='unit_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
