# Generated by Django 5.1.5 on 2025-03-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('customers', '0002_address_city_code_address_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='address.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
