# Generated by Django 5.1.5 on 2025-08-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_customer_address_delete_address"),
    ]

    operations = []
