# Generated by Django 5.1.5 on 2025-08-25 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_remove_book_cover_image_remove_book_cover_type_and_more"),
        ("customers", "0004_rename_book_to_bookformat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="book",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="book",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="book_format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="books.bookformat",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="book_format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="books.bookformat",
            ),
        ),
    ]
