# Generated by Django 5.1.5 on 2025-08-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_rename_discount_code_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="is_preorder",
            field=models.BooleanField(default=False),
        ),
    ]
