# Generated by Django 5.1.5 on 2025-08-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_bookformat_preorder_end_date_bookformat_status"),
        ("customers", "0007_invoiceitem_is_preorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="books.bookformat",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "unique_together": {("customer", "book_format")},
            },
        ),
    ]
