# Generated by Django 5.1.5 on 2025-08-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
