# Generated by Django 5.1.5 on 2025-03-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_type', models.CharField(blank=True, choices=[('1', 'محل دائمی سکونت | مالک هستم | بیش از دو سال در این مکان هستم'), ('2', 'محل دائمی سکونت | مالک هستم | بیش از یکسال و کمتر از دو سال در این مکان هستم'), ('3', 'محل دائمی سکونت | مالک هستم | بزودی تغییر مکان می دهم'), ('4', 'محل دائمی سکونت | مستاجر هستم | بیش از یکسال در این مکان هستم'), ('5', 'محل دائمی سکونت | مستاجر هستم | کمتر از یکسال در این مکان هستم'), ('6', 'محل موقت سکونت | در ایران ساکن نیستم و ساکن کشور دیگری هستم'), ('7', 'محل موقت سکونت | مالک هستم | ساکن شهر دیگری هستم'), ('8', 'محل موقتی سکونت | نه مالک و نه مستاجر هستم | بزودی تغییر مکان می دهم'), ('9', 'محل دائمی کار و تجارت | مالک یا مستاجر هستم | بتازگی در این مکان هستم )کمتر از دوماه('), ('10', 'محل دائمی کار و تجارت | مالک هستم | بیش از یکسال در این مکان هستم'), ('11', 'محل دائمی کار و تجارت | مالک هستم | کمتر از یکسال در این مکان هستم )بیش از دو ماه('), ('12', 'محل دائمی کار و تجارت | مستاجر هستم | بیش از یکسال در این مکان هستم'), ('13', 'محل دائمی کار و تجارت | مستاجر هستم | کمتر از یکسال در این مکان هستم )بیش از دو ماه(')], default=None, max_length=2, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('province_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('city_code', models.CharField(blank=True, max_length=10, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('unit_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
